// calcs the total tdv for a day (pivots off (L) {local} values in a cell)
=MULTIPLY({cost col}, SUMPRODUCT(LEN({comp col})-LEN(SUBSTITUTE({comp col}, "(L)", "()"))))

// EX: implemented for Sat values in Google Sheets
=MULTIPLY(A3, SUMPRODUCT(LEN(C3)-LEN(SUBSTITUTE(C3,"(L)","()"))))+MULTIPLY(A4, SUMPRODUCT(LEN(C4)-LEN(SUBSTITUTE(C4,"(L)","()"))))+MULTIPLY(A5, SUMPRODUCT(LEN(C5)-LEN(SUBSTITUTE(C5,"(L)","()"))))+MULTIPLY(A6, SUMPRODUCT(LEN(C6)-LEN(SUBSTITUTE(C6,"(L)","()"))))+MULTIPLY(A7, SUMPRODUCT(LEN(C7)-LEN(SUBSTITUTE(C7,"(L)","()"))))+MULTIPLY(A8, SUMPRODUCT(LEN(C8)-LEN(SUBSTITUTE(C8,"(L)","()"))))+MULTIPLY(A9, SUMPRODUCT(LEN(C9)-LEN(SUBSTITUTE(C9,"(L)","()"))))+MULTIPLY(A10, SUMPRODUCT(LEN(C10)-LEN(SUBSTITUTE(C10,"(L)","()"))))+MULTIPLY(A11, SUMPRODUCT(LEN(C11)-LEN(SUBSTITUTE(C11,"(L)","()"))))+MULTIPLY(A12, SUMPRODUCT(LEN(C12)-LEN(SUBSTITUTE(C12,"(L)","()"))))+MULTIPLY(A13, SUMPRODUCT(LEN(C13)-LEN(SUBSTITUTE(C13,"(L)","()"))))+MULTIPLY(A14, SUMPRODUCT(LEN(C14)-LEN(SUBSTITUTE(C14,"(L)","()"))))+MULTIPLY(A15, SUMPRODUCT(LEN(C15)-LEN(SUBSTITUTE(C15,"(L)","()"))))+MULTIPLY(A16, SUMPRODUCT(LEN(C16)-LEN(SUBSTITUTE(C16,"(L)","()"))))+MULTIPLY(A17, SUMPRODUCT(LEN(C17)-LEN(SUBSTITUTE(C17,"(L)","()"))))

// A3:A17 is the range for cost associated to a course
// C-I3:C-I17 is the range for a week of values
