// calcs the total tdv for a day (pivots off (O) {online} values in a cell)
=MULTIPLY({cost col}, SUMPRODUCT(LEN({comp col})-LEN(SUBSTITUTE({comp col}, "(O)", "()"))))

// EX: implemented for Sat values in Google Sheets
=MULTIPLY(A3, SUMPRODUCT(LEN(C3)-LEN(SUBSTITUTE(C3,"(O)","()"))))+MULTIPLY(A4, SUMPRODUCT(LEN(C4)-LEN(SUBSTITUTE(C4,"(O)","()"))))+MULTIPLY(A5, SUMPRODUCT(LEN(C5)-LEN(SUBSTITUTE(C5,"(O)","()"))))+MULTIPLY(A6, SUMPRODUCT(LEN(C6)-LEN(SUBSTITUTE(C6,"(O)","()"))))+MULTIPLY(A7, SUMPRODUCT(LEN(C7)-LEN(SUBSTITUTE(C7,"(O)","()"))))+MULTIPLY(A8, SUMPRODUCT(LEN(C8)-LEN(SUBSTITUTE(C8,"(O)","()"))))+MULTIPLY(A9, SUMPRODUCT(LEN(C9)-LEN(SUBSTITUTE(C9,"(O)","()"))))+MULTIPLY(A10, SUMPRODUCT(LEN(C10)-LEN(SUBSTITUTE(C10,"(O)","()"))))+MULTIPLY(A11, SUMPRODUCT(LEN(C11)-LEN(SUBSTITUTE(C11,"(O)","()"))))+MULTIPLY(A12, SUMPRODUCT(LEN(C12)-LEN(SUBSTITUTE(C12,"(O)","()"))))+MULTIPLY(A13, SUMPRODUCT(LEN(C13)-LEN(SUBSTITUTE(C13,"(O)","()"))))+MULTIPLY(A14, SUMPRODUCT(LEN(C14)-LEN(SUBSTITUTE(C14,"(O)","()"))))+MULTIPLY(A15, SUMPRODUCT(LEN(C15)-LEN(SUBSTITUTE(C15,"(O)","()"))))+MULTIPLY(A16, SUMPRODUCT(LEN(C16)-LEN(SUBSTITUTE(C16,"(O)","()"))))+MULTIPLY(A17, SUMPRODUCT(LEN(C17)-LEN(SUBSTITUTE(C17,"(O)","()"))))

// A3:A17 is the range for cost associated to a course
// C-I3:C-I17 is the range for a week of values
