// calcs the total tdv for a day (pivots off (O) {online} values in a cell)
=MULTIPLY({cost col}, SUMPRODUCT(LEN({comp col})-LEN(SUBSTITUTE({comp col}, "(O)", "()"))))

// EX: implemented for Sat values in Google Sheets
=MULTIPLY(A62, SUMPRODUCT(LEN(C62)-LEN(SUBSTITUTE(C62,"(O)","()"))))+MULTIPLY(A63, SUMPRODUCT(LEN(C63)-LEN(SUBSTITUTE(C63,"(O)","()"))))+MULTIPLY(A64, SUMPRODUCT(LEN(C64)-LEN(SUBSTITUTE(C64,"(O)","()"))))+MULTIPLY(A65, SUMPRODUCT(LEN(C65)-LEN(SUBSTITUTE(C65,"(O)","()"))))+MULTIPLY(A66, SUMPRODUCT(LEN(C66)-LEN(SUBSTITUTE(C66,"(O)","()"))))+MULTIPLY(A67, SUMPRODUCT(LEN(C67)-LEN(SUBSTITUTE(C67,"(O)","()"))))+MULTIPLY(A68, SUMPRODUCT(LEN(C68)-LEN(SUBSTITUTE(C68,"(O)","()"))))+MULTIPLY(A69, SUMPRODUCT(LEN(C69)-LEN(SUBSTITUTE(C69,"(O)","()"))))+MULTIPLY(A70, SUMPRODUCT(LEN(C70)-LEN(SUBSTITUTE(C70,"(O)","()"))))+MULTIPLY(A71, SUMPRODUCT(LEN(C71)-LEN(SUBSTITUTE(C71,"(O)","()"))))+MULTIPLY(A72, SUMPRODUCT(LEN(C72)-LEN(SUBSTITUTE(C72,"(O)","()"))))+MULTIPLY(A73, SUMPRODUCT(LEN(C73)-LEN(SUBSTITUTE(C73,"(O)","()"))))+MULTIPLY(A74, SUMPRODUCT(LEN(C74)-LEN(SUBSTITUTE(C74,"(O)","()"))))+MULTIPLY(A75, SUMPRODUCT(LEN(C75)-LEN(SUBSTITUTE(C75,"(O)","()"))))+MULTIPLY(A76, SUMPRODUCT(LEN(C76)-LEN(SUBSTITUTE(C76,"(O)","()"))))

// A62:A76 is the range for cost associated to a course
// C-I62:C-I76 is the range for a week of values

// CTRL+H in notepad and replace C6 w/ D6 && C7 w/ D7 (repeat for E-I)