// calcs the total tdv for a day (pivots off (O) {online} values in a cell)
=MULTIPLY({cost col}, SUMPRODUCT(LEN({comp col})-LEN(SUBSTITUTE({comp col}, "(O)", "()"))))

// EX: implemented for Sat values in Google Sheets
=MULTIPLY(A32, SUMPRODUCT(LEN(C32)-LEN(SUBSTITUTE(C32,"(O)","()"))))+MULTIPLY(A33, SUMPRODUCT(LEN(C33)-LEN(SUBSTITUTE(C33,"(O)","()"))))+MULTIPLY(A34, SUMPRODUCT(LEN(C34)-LEN(SUBSTITUTE(C34,"(O)","()"))))+MULTIPLY(A35, SUMPRODUCT(LEN(C35)-LEN(SUBSTITUTE(C35,"(O)","()"))))+MULTIPLY(A36, SUMPRODUCT(LEN(C36)-LEN(SUBSTITUTE(C36,"(O)","()"))))+MULTIPLY(A37, SUMPRODUCT(LEN(C37)-LEN(SUBSTITUTE(C37,"(O)","()"))))+MULTIPLY(A38, SUMPRODUCT(LEN(C38)-LEN(SUBSTITUTE(C38,"(O)","()"))))+MULTIPLY(A39, SUMPRODUCT(LEN(C39)-LEN(SUBSTITUTE(C39,"(O)","()"))))+MULTIPLY(A40, SUMPRODUCT(LEN(C40)-LEN(SUBSTITUTE(C40,"(O)","()"))))+MULTIPLY(A41, SUMPRODUCT(LEN(C41)-LEN(SUBSTITUTE(C41,"(O)","()"))))+MULTIPLY(A42, SUMPRODUCT(LEN(C42)-LEN(SUBSTITUTE(C42,"(O)","()"))))+MULTIPLY(A43, SUMPRODUCT(LEN(C43)-LEN(SUBSTITUTE(C43,"(O)","()"))))+MULTIPLY(A44, SUMPRODUCT(LEN(C44)-LEN(SUBSTITUTE(C44,"(O)","()"))))+MULTIPLY(A45, SUMPRODUCT(LEN(C45)-LEN(SUBSTITUTE(C45,"(O)","()"))))+MULTIPLY(A46, SUMPRODUCT(LEN(C46)-LEN(SUBSTITUTE(C46,"(O)","()"))))

// A32:A46 is the range for cost associated to a course
// C-I32:C-I46 is the range for a week of values

// CTRL+H in notepad and replace C3 w/ D3 && C4 w/ D4 (repeat for E-I)